In [28]:
import numpy as np
import math
def randInstanceGen(n,m,J,U):
    # Reset seed for safety
    np.random.seed(0)
    # Set seed
    np.random.seed(61836)
    
    c = np.random.randint(1,U+1,(J,n))
    a = np.random.randint(1,U+1,(n,m))
    
    b = np.max(a, axis=0)
    
    for i in range(0, m):
        if math.ceil(np.sum(a[:,i])/2) > b[i]:
            b[i] = math.ceil(np.sum(a[:,i])/2)
    
    return c.reshape(-1), a, b

In [29]:
c, a, b = randInstanceGen(5,3,1,40)
print(c)
print("**")
print(a)
print("**")
print(b)

[34  1 37 17  1]
**
[[40  3 32]
 [31  7 29]
 [22 12 40]
 [20  2 23]
 [ 7  7 31]]
**
[60 16 78]


In [20]:
import gurobipy as gp
from gurobipy import GRB

In [79]:
n = 5
J = 1
M = 1
U = 40

c, a, b = randInstanceGen(n,M,J,U)

m = gp.Model("Checkpoint Q4/5")

Items=list(np.arange(0,n))
Dimensions= list(np.arange(0,M))

# Decision Vars
x = m.addVars(n,vtype=GRB.BINARY, name="ToTakeOrNotToTake")

m.setObjective(gp.quicksum(x[i]*c[i] for i in Items), GRB.MAXIMIZE)

for j in Dimensions:
    m.addConstr(gp.quicksum(x[i]*a[i,j] for i in Items) <= b[j], name="j")

m.optimize()

print("***********Values**********")

Mat = np.zeros((1,5))
i = 0
j = 0
for p in x:
    if j == Mat.shape[1]:
        j = 0
        i += 1
    Mat[i,j] = abs(x[p].x)
    j+=1

print(Mat)
    
print('Obj: ',m.objVal)

Gurobi Optimizer version 9.0.0 build v9.0.0rc2 (win64)
Optimize a model with 1 rows, 5 columns and 5 nonzeros
Model fingerprint: 0xd02e4222
Variable types: 0 continuous, 5 integer (5 binary)
Coefficient statistics:
  Matrix range     [3e+00, 4e+01]
  Objective range  [1e+00, 4e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [6e+01, 6e+01]
Found heuristic solution: objective 36.0000000
Presolve removed 1 rows and 5 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 39 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.900000000000e+01, best bound 3.900000000000e+01, gap 0.0000%
***********Values**********
[[0. 1. 1. 0. 1.]]
Obj:  39.0


In [80]:
for i in m.getConstrs():
    i.RHS = i.RHS * 1.5
for i in m.getVars():
    i.Obj = i.Obj/2

m.optimize()

print("***********Values**********")

Mat = np.zeros((1,5))
i = 0
j = 0
for p in x:
    if j == Mat.shape[1]:
        j = 0
        i += 1
    Mat[i,j] = abs(x[p].x)
    j+=1

print(Mat)
    
print('Obj: ',m.objVal)

Gurobi Optimizer version 9.0.0 build v9.0.0rc2 (win64)
Optimize a model with 1 rows, 5 columns and 5 nonzeros
Model fingerprint: 0xb6d69afa
Variable types: 0 continuous, 5 integer (5 binary)
Coefficient statistics:
  Matrix range     [3e+00, 4e+01]
  Objective range  [5e-01, 2e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [9e+01, 9e+01]

Loaded MIP start from previous solve with objective 19.5

Presolve removed 1 rows and 5 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 36.5 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.650000000000e+01, best bound 3.650000000000e+01, gap 0.0000%
***********Values**********
[[1. 1. 1. 0. 1.]]
Obj:  36.5
