In [64]:
import numpy as np
a = np.array([[-20,-2,-2],[-15,-3,-3],[-13,-3,-3],[-10,-10,-10],[-10,-9,-11],[-10,-8,-12],[-10,-6,-14],[-10,-5,-15],[-8,-20,-20],[-8,-20,-20]])

In [65]:
a

array([[-20,  -2,  -2],
       [-15,  -3,  -3],
       [-13,  -3,  -3],
       [-10, -10, -10],
       [-10,  -9, -11],
       [-10,  -8, -12],
       [-10,  -6, -14],
       [-10,  -5, -15],
       [ -8, -20, -20],
       [ -8, -20, -20]])

In [77]:
def insertinto(a, line):
    from math import floor as fl
    #first find middle
    if a is None:
        return line.reshape(-1,3)
    start = 0
    end = a.shape[0]
    
    if line[0] > a[-1,0]:
        return np.vstack((a,line))
    if line[0] < a[0,0]:
        return np.vstack((line,a))
    while end > start:
        pull = fl((end+start)/2.0)
        if a[pull,0] == line[0]:
            break
        elif a[pull,0] < line[0]:
            if a[pull+1,0] > line[0]:
                return np.insert(a,pull+1,line,axis=0)
            start = pull+1
        else:
            if a[pull-1,0] < line[0]:
                return np.insert(a,pull,line,axis=0)
            end = pull-1
    #now go backwards:
    anchor = pull
    if end == start:
        anchor = end
        pull = anchor
    while True:
        pull -= 1
        if pull == -1:
            anchorstart = 0
            break
        if a[pull,0] != line[0]:
            anchorstart = pull + 1
            break
    pull = anchor
    while True:
        pull += 1
        if pull == a.shape[0]:
            anchorend = pull - 1
            break
        if a[pull,0] != line[0]:
            anchorend = pull - 1
            break
    start = anchorstart
    end = anchorend
    
    level1start = anchorstart
    level1end = anchorend
    
    
    if line[1] > a[end,1]:
        return np.insert(a,end+1,line,axis=0)
    if line[1] < a[start,1]:
        return np.insert(a,start,line,axis=0)
    while True:
        pull = fl((end+start)/2.0)
        if a[pull,1] == line[1]:
            break
        elif a[pull,1] < line[1]:
            if a[pull+1,1] > line[1]:
                return np.insert(a,pull+1,line,axis=0)
            start = pull+1
        else:
            if a[pull-1,1] < line[1]:
                return np.insert(a,pull,line,axis=0)
            end = pull-1
    anchor = pull
    if end == start:
        anchor = end
        pull = anchor
    print(anchor)
    while True:
        pull -= 1
        if pull == -1:
            anchorstart = level1start
            break
        if a[pull,1] != line[1]:
            anchorstart = pull + 1
            break
    pull = anchor
    
    while True:
        pull += 1
        if pull == a.shape[0]:
            anchorend = level1end
            break
        if a[pull,1] != line[1]:
            anchorend = pull - 1
            break
    start = anchorstart
    end = anchorend
    

    if line[2] > a[end,2]:
        return np.insert(a,end+1,line,axis=0)
    if line[2] < a[start,2]:
        return np.insert(a,start,line,axis=0)
    while True:
        pull = fl((end+start)/2.0)
        if a[pull,2] == line[2]:
            print("FUCKING CRY")
        elif a[pull,2] < line[2]:
            if a[pull+1,2] > line[2]:
                return np.insert(a,pull+1,line,axis=0)
            start = pull+1
        else:
            if a[pull-1,2] < line[2]:
                return np.insert(a,pull,line,axis=0)
            end = pull-1

In [79]:
insertinto(a,[-10,-6,-13])

6


array([[-20,  -2,  -2],
       [-15,  -3,  -3],
       [-13,  -3,  -3],
       [-10, -10, -10],
       [-10,  -9, -11],
       [-10,  -8, -12],
       [-10,  -6, -14],
       [-10,  -6, -13],
       [-10,  -5, -15],
       [ -8, -20, -20],
       [ -8, -20, -20]])

In [61]:
test = np.array([[-7116.0, 0, 0], [-6877.0, -7060.0, 0], [-6877.0, 0, -5079.0], [-7116.0, -7049.0, 0], [-6811.0, -7060.0, 0], [-6811.0, -7049.0, -5079.0], [-6835.0, 0, -5432.0], [-6776.0, -6303.0, -5432.0], [-6776.0, 0, -5559.0], [-6710.0, -7199.0, -5144.0], [-6682.0, -7340.0, -5144.0], [-6682.0, -7199.0, -5158.0], [-6608.0, 0, -5596.0], [-6591.0, -6080.0, -5596.0], [-6591.0, 0, -5694.0], [-6535.0, 0, -5774.0], [-6521.0, -6451.0, -5774.0], [-6521.0, 0, -5914.0], [-6535.0, 0, -5863.0], [-6471.0, -6451.0, -5863.0], [-6471.0, 0, -5914.0], [-6354.0, -7799.0, 0], [-6242.0, -7833.0, 0], [-6242.0, -7799.0, -4776.0], [-6103.0, -7887.0, -5423.0], [-5940.0, -8079.0, -5423.0], [-5940.0, -7887.0, -5437.0], [-6103.0, -8068.0, -5423.0], [-5722.0, -8079.0, -5423.0], [-5722.0, -8068.0, -5437.0], [-5445.0, -8068.0, -5657.0], [0, -8235.0, -5657.0], [0, -8068.0, -5734.0], [-5034.0, -7828.0, -6152.0], [0, -7886.0, -6152.0], [0, -7828.0, -6462.0], [-5760.0, -7314.0, -6237.0], [-5474.0, -7320.0, -6237.0], [-5474.0, -7314.0, -6365.0], [-5760.0, -7314.0, -6287.0], [0, -7320.0, -6287.0], [0, -7314.0, -6365.0], [-5952.0, 0, -6291.0], [-5931.0, -6906.0, -6291.0], [-5931.0, 0, -6304.0], [-5789.0, -6797.0, -6291.0], [-5760.0, -7006.0, -6291.0], [-5760.0, -6797.0, -6402.0], [-5789.0, -6797.0, -6365.0], [-5741.0, -7006.0, -6365.0], [-5741.0, -6797.0, -6402.0], [-5301.0, -7228.0, -6365.0], [-5034.0, -7286.0, -6365.0], [-5034.0, -7228.0, -6700.0], [-5301.0, -7228.0, -6462.0], [0, -7286.0, -6462.0], [0, -7228.0, -6700.0], [-5320.0, -7006.0, -6525.0], [-5301.0, -7378.0, -6525.0], [-5301.0, -7006.0, -6540.0], [-5606.0, 0, -6621.0], [-5301.0, -6722.0, -6621.0], [-5301.0, 0, -6635.0], [-5100.0, 0, -6700.0], [0, -7311.0, -6700.0], [0, 0, -6750.0]])

In [62]:
a = None
for i in test:
    a = insertinto(a,i)
print(a)

[[-7116. -7049.     0.]
 [-7116.     0.     0.]
 [-6877. -7060.     0.]
 [-6877.     0. -5079.]
 [-6835.     0. -5432.]
 [-6811. -7060.     0.]
 [-6811. -7049. -5079.]
 [-6776. -6303. -5432.]
 [-6776.     0. -5559.]
 [-6710. -7199. -5144.]
 [-6682. -7340. -5144.]
 [-6682. -7199. -5158.]
 [-6608.     0. -5596.]
 [-6591. -6080. -5596.]
 [-6535.     0. -5863.]
 [-6591.     0. -5694.]
 [-6535.     0. -5774.]
 [-6521. -6451. -5774.]
 [-6521.     0. -5914.]
 [-6471. -6451. -5863.]
 [-6471.     0. -5914.]
 [-6354. -7799.     0.]
 [-6242. -7833.     0.]
 [-6242. -7799. -4776.]
 [-6103. -8068. -5423.]
 [-6103. -7887. -5423.]
 [-5952.     0. -6291.]
 [-5940. -8079. -5423.]
 [-5940. -7887. -5437.]
 [-5931. -6906. -6291.]
 [-5931.     0. -6304.]
 [-5789. -6797. -6365.]
 [-5789. -6797. -6291.]
 [-5760. -7314. -6287.]
 [-5760. -7314. -6237.]
 [-5760. -7006. -6291.]
 [-5760. -6797. -6402.]
 [-5741. -7006. -6365.]
 [-5741. -6797. -6402.]
 [-5722. -8079. -5423.]
 [-5722. -8068. -5437.]
 [-5606.     0. 